### ISSUE TITLE
cmake errors on switch file with STAB3 and only one of ST4, ST3

### ISSUE THREAD

**Issue by camilleanne** [NOAA-EMC/WW3#1082]
**Describe the bug**
When building with cmake, if the switch file includes `STAB3` then `ST3` and `ST4` are both required, but it should allow just one. 

**To Reproduce**
Steps to reproduce the behavior. 
If you have a switch file that includes `STAB3 ST4` and follow [the cmake instructions](https://github.com/NOAA-EMC/WW3/blob/develop/model/README.md#quick-start) `cmake .. -DSWITCH=/path/to/switch_CMAKE_TEST` you'll see the error: `error: Switch 'STAB3' requires 'ST3' to be set`

_enumerated combinations:_
switch file includes: `STAB3 ST4`
error: `Switch 'STAB3' requires 'ST3' to be set`

switch file includes: `STAB3 ST3`
error: `Switch 'STAB3' requires 'ST4' to be set`

switch file includes: `STAB3 ST4 ST3`
error: `No valid sterm switches found, but one is required`

switch file includes: `ST4 ST3`
error: `No valid sterm switches found, but one is required`

switch file includes: `ST4`
error: none

switch file includes: `ST3`
error: none

**Expected behavior**
I expect that either `ST3` or `ST4` would be required to be used with `STAB3`, not that both are required. I have no sense about whether it's appropriate to use both together with `STAB3`, but know that our use case only requires `STAB3` and `ST4`.

[The manual](https://github.com/NOAA-EMC/WW3/blob/8589d12a46c3824891fd43f372a98e2732e2c220/manual/eqs/ST4.tex#L45C1-L45C103) asserts either `ST3` or `ST4` can be used with `STAB3`, implying that both are not required:
> The STAB3 switch, described above for use with ST3, may also be used with ST4. 

This is corroborated by [the older build_utils logic](https://github.com/NOAA-EMC/WW3/blob/8589d12a46c3824891fd43f372a98e2732e2c220/model/bin/build_utils.sh#L485-L493).

**Additional context**
I believe this behavior originates from [this line in switches.json](https://github.com/NOAA-EMC/WW3/blob/develop/model/src/cmake/switches.json#L267).

**Comment by MatthewMasarik-NOAA** [comment]
@camilleanne Thanks for reporting and documenting this!  I think your assessment is spot on, this is a bug, and either `ST4` or `ST3` need to be selected when `STAB3` is present, (selecting both `ST4` _and_ `ST3` should not be allowed).  I did run into this earlier this year working with `STAB3`, but unfortunately it was lower priority at the time and fell off my plate..  We don't use the `STAB3` switch in any of our regtests currently, so that was part of the lower priority.  

This should be an easy fix of the logic though, in the switches.json file you pointed to, assuming no side effects that might not be obvious yet.  I'll start on testing that fix.  @JessicaMeixner-NOAA is back Monday, and I have some leave next week, so likely she can pick up with what I have.  I see a timeline of getting something submitted & approved likely end of next week, or early the following.  Monday we will have a better idea of timing.

**Comment by MatthewMasarik-NOAA** [comment]
@camilleanne  I have fix that I believe corrects the build w.r.t. `STAB3` using `ST3` _or_ `ST4`.  I've confirmed it behaves correctly when each combination is selected, now I have the normal set of regression tests running to verify the fix did not change those.  If all goes well I can submit a PR tomorrow, then @JessicaMeixner-NOAA will take over for the PR review.

**Comment by MatthewMasarik-NOAA** [comment]
Fyi @camilleanne, the PR was submitted.  I'm on leave now till friday.  @JessicaMeixner-NOAA  will handle the review from here.

**Comment by MatthewMasarik-NOAA** [comment]
fyi @camilleanne.  Thanks for your patience!
