### ISSUE TITLE
 code stability test failed in ww3_outp

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [NOAA-EMC/WW3#1173]
The debug build for ww3_outp failed with two issues(in w3bullmd.F90)[[#249](https://github.com/hafs-community/HAFS/issues/249)]:

### Issue 1.
- Shape mismatch: The extent of dimension 1 of array HSP is 80 and the corresponding extent of array XPART is 1
- Shape mismatch: The extent of dimension 1 of array TPP is 80 and the corresponding extent of array XPART is 1
The relevant lines in w3bullmd.F90 are 
```
HSP = XPART(1,1:NPART)
TPP = XPART(2,1:NPART)
```
### Issue 2.
IPG1 is not initialized in w3bullmd.F90
The relevant line in w3bullmd.F90 is

`IPI(IFLD)=IPG1+1`

The HAFS repository: 
https://github.com/hafs-community/WW3/tree/c96ce38f460fee42601b763a5d9027a8350c70fb/model/src

**Comment by BijuThomas-NOAA** [comment]
@MatthewMasarik-NOAA Wondering if you get a chance to look into issue#1173

**Comment by BinLiu-NOAA** [comment]
@BijuThomas-NOAA, With the communication with the FOM and our wave modeling team, @AliS-Noaa currently is the main POC (@sbanihash is the backup POC) for HAFSv2 WW3 related upgrades/validation from the wave modeling team.

With that, @MatthewMasarik-NOAA and @JessicaMeixner-NOAA, if you have any in-kind comments/suggestions, that will be much appreciated. Meanwhile, @AliS-Noaa and @sbanihash, please help to look into this issue #1173 and the related context from hafs-community/HAFS/issues/249. Thanks!

**Comment by MatthewMasarik-NOAA** [comment]
Hi @BinLiu-NOAA @BijuThomas-NOAA @AliS-Noaa @sbanihash 

I looked at the reports Biju has provided, and I haven't encountered this before.  We don't compile with the new flags NCO plans to add for this update, so this is not surprising.  There seems to be some good hints from Biju, though.  In the header of this issue there were two specific errors pointed out, an index out of range, and uninitialized value.  From the associated HAFS issue (https://github.com/hafs-community/HAFS/issues/249), a traceback is provided, which has the line number for the array out of bounds error.  I would start there.  Possibly you have to get past the first error to get to Issue 2. in the traceback?  The SPA's run directory would be helpful to follow up on.  Since we haven't built with those flags before, I would also verify with the SPA their proposed build details.  Feel free to reach out with questions.
