### ISSUE TITLE
netcdf fails to link on some systems: correct libs= statements

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#15]
Some link scripts need to be bugfixed for libs= statement that removes netcdf libs= settings. This occurs in link.theia but may occur in other scripts.

**Comment by JessicaMeixner-NOAA** [comment]
I'm not sure I understand your issue. How can I replicate this issue?

**Comment by ajhenrique** [comment]
Try to compile the netcdf wrapper on Theia (NCEP's R&D machine) using comp.theia and link.theia. I have a fix for this and will implement on the develop branch.

**Comment by JessicaMeixner-NOAA** [comment]
So if  on theia I do:  

git clone https://github.com/NOAA-EMC/WW3
cd WW3 
./setup model -c theia -s ??? 
./w3_make ww3_??? 

What are the ???

**Comment by mickaelaccensi** [comment]
could you try to use the cmplr.env system with:
 ./w3_setup model -c intel ( instead of theia )
in comp.theia and link.theia, I'm surprised the way the compiler can be defined as mpiifort or ifort -lmpi. It would be better to either compile with -c intel or -c mpt... anyway can you send your error message in the linking.

**Comment by j-gonzalezlopez** [comment]
Maybe not directly related, but I've had issues compiling for GRIB1/GRIB2 and NetCDF (using gfortran-8). The link.tmpl file doesn't include the if statement to assign the GRIB1 library to compile ww3_grib. I managed to successfully compile for GRIB1 by copying those lines from link.xlf into the link file created after calling ww3_setup the first time. Still working on getting the compilation to work for GRIB2 and NetCDF. If this should be put into another new issue please let me know.

**Comment by JessicaMeixner-NOAA** [comment]
@j-gonzalezlopez   If you want to compile with GRIB, I'd recommend looking at the comp/link.{theia, wcoss*} ones. 

@mickaelaccensi :  @ajhenrique and I discussed this morning about cleaning up all the comp.* link.* files so that we are using the cmplr.env system for everything (I think we talked about this a long time ago but I asked to wait until after the public release to do this).    So we need to make updates to 
model/bin/{w3_setup, cmpl.env, link.tmp and comp.tmp} so that when w3_setup is called: 
     source $path_b/cmplr.env
sed -e "s/<optl>/$optl/" -e "s/<comp_seq>/$comp_seq/" -e "s/<comp_mpi>/$comp_mpi/" $path_b/link.tmpl > $path_b/link

and 

 sed -e "s/<optc>/$optc/" -e "s/<comp_seq>/$comp_seq/" -e "s/<comp_mpi>/$comp_mpi/" $path_b/comp.tmpl > $path_b/comp

happen we get the right options.  On a side note, in the future, we might make an option to where we get some of these compile options from a higher level script (for example when compiling in a coupled model).

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi Another question:  Do you know who the zeus_* references are for?  I know NOAA used to have a zeus, so I just want to confirm it is that so we can update those and make sure I'm not erasing something someone else needed.

**Comment by mickaelaccensi** [comment]
I totally agree with the idea of cleaning up all the comp and link files and just keep the comp.tmpl and link.tmpl !

about the zeus, I think it was only used at NOAA.

**Comment by ajhenrique** [comment]
I'll start a feature branch of my fork and add the changes for grib to comp.tmpl and link.tmpl for the develop branch. We can discuss approach for eliminating comp and link files during our repo managers meeting on May 6th.

**Comment by ajhenrique** [comment]
This issue had morphed into the generalization of comp/link scripts using cmplr.env and single comp.tmpl and link.tmpl scripts.
