### ISSUE TITLE
Internal version number of out_pnt.ww3 needs updating

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#152]
The binary format of the `out_pnt.ww3` has changed somewhat over the past few years, but the internal file version identitifier has not changed for a long time:

```
    CHARACTER(LEN=10), PARAMETER, PRIVATE :: VEROPT = 'III  2.01 '
```

I propose that every time the binary format of this file changes, the version number should be increased (and this should be looked out for by reviewers when performing PR reviews). The same rule should also be applied to all the other `*.ww3` binary output files that store an internal revision number.

Whilst this does not have any impact on the use of other WW3 post-processing programs, it may impact other (non-WW3) code that might read those files.

I'm not sure on the versioning scheme - I assume it ia related to the WW3 release verision? If so, can we update the number to `'III 7.00'` to reflect the upcoming release?

**Comment by JessicaMeixner-NOAA** [comment]
There's several places in the code with version numbers, such as in w3iogrmd.ftn has VERGRD.     I know I used to check for that and it's a part of this checklist: 
https://github.com/NOAA-EMC/WW3/wiki/Code-Management#checklist-for-a-developer-submitting-to-develop

We should add VEROPT to that list, and any others (which may or may not have been properly updated as we went). The strategy I previously used, was if w3iogrmd got updated, then VERGRD got updated, but it used a date which was a little more straight forward to update.   I think the idea for having these is so that you will not try to process a binary file that was not made with the correct version of the code.

**Comment by ukmo-ccbunney** [comment]
Do you think that using a date (rather than version number) would be suitable for the other binary files that set VEROPT?

**Comment by JessicaMeixner-NOAA** [comment]
Dates or some way of distinguishing that particular number (from other version numbers) where it just gets incremented by 1 could work?  I think dates would be simpler.  I don't know if there's any history of why there were other numbers or where they came from originally though.

**Comment by ajhenrique** [comment]
This issue has been solved.
