### ISSUE TITLE
wind.ww3 generation error

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [NOAA-EMC/WW3#158]
Hi everyone

I tried to generate wind.ww3 but I got this error:

 *** WAVEWATCH III  Input pre-processing ***  
               ===============================================

  Comment character is '$'

  Grid name : Single Domain 1/2 gedree      

  Description of inputs
 --------------------------------------------------
       Input type        : winds       
       Format type       : long.-lat. grid     
          Field corrected for energy conservation.

       Input grid dim.   :  421     261
       Longitude range   :  110.00  320.00 (deg)
       Latitude range    :  -65.00   65.00 (deg)

  Preprocessing data
 --------------------------------------------------
       Interpolation factors ..... 
          (longitude-latitude grid)

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7fb07d12531a
#1  0x7fb07d124503
#2  0x7fb07c582f1f
#3  0x7fb07c5db98d
#4  0x562220c921d9
#5  0x562220c8fc98
#6  0x7fb07c565b96
#7  0x562220c8fcc9
#8  0xffffffffffffffff
Segmentation fault (core dumped)

what kind of error is this? How can I resolve?

Thanks in advance guys!

[ww3_prep_inp.txt](https://github.com/NOAA-EMC/WW3/files/4099129/ww3_prep_inp.txt)
[switch.txt](https://github.com/NOAA-EMC/WW3/files/4099130/switch.txt)

**Comment by ajhenrique** [comment]
Hi @DiegoGutierrez2210 your issue is not exactly a code development issue, it is more like a user needing help with a problem in executing the code. Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users

Or send an email to us at NCEP: NCEP.List.WAVEWATCH@noaa.gov
