### ISSUE TITLE
Extend parameter set for coupled modelling 

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#206]
Enhancement to extend output parameter set and restart file storage options required for coupled atmosphere-wave-ocean modelling. The extensions are based on Met Office testing with UM-WWIII-NEMO models coupled via OASIS

**Comment by ukmo-juan-castillo** [comment]
Some changes in the code are required to allow the coupling of some extra wave variables to atmosphere and ocean models, just by adding them to the list of fields available for coupling. Furthermore, a new series of variables required for coupling need to be calculated in the source terms, such as the wind stress transferred to the ocean. All the fields that are in the 'send' coupling list need to be written in the wave restart file, if the source terms are not calculated before the first time step of the model. This is required in order for the coupling fields sent to other models to contain appropriate values at the first time step, when coupling always takes place, in order to preserve the continuity of a 'cycling' run.

**Comment by ukmo-ansaulter** [comment]
@ukmo-juan-castillo will be the main developer for these changes

@JessicaMeixner-NOAA these changes will include some work very similar to your WRST changes, so hopefully OK to check in with you for some advice/review as we go along?

**Comment by JessicaMeixner-NOAA** [comment]
of course @ukmo-ansaulter  

I have a feeling we might need more variables for restart reproducibility in the ESMF coupling as well for variables not calculated until after the first time step.

**Comment by ukmo-juan-castillo** [comment]
> of course @ukmo-ansaulter
> 
> I have a feeling we might need more variables for restart reproducibility in the ESMF coupling as well for variables not calculated until after the first time step.

This has already been tackled in issue #232, and now it is possible to include a list of variables in the restart file via a namelist variable. At the moment only variables that can be exchanged via OASIS coupling can be written to the restart, but modifying the code to add new fields is straightforward.
