### ISSUE TITLE
Gaps in wave data

### ISSUE THREAD

**Issue by jianke777** [NOAA-EMC/WW3#212]
We are a user a NOAA's wave data. One thing that bothers us about the data is that there are a lot of gaps in the significant height of wind waves. I wonder if someone could help me understand these gaps, such as why they are there, and what these gaps represent. Thanks.

**Comment by aliabdolali** [comment]
Hi @jianke777 your issue is not exactly a code development issue and is not clearly explained, it is more like a user needing help with a problem in executing the code (if this is the case). Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users
