### ISSUE TITLE
Why are there gaps in swell and wind wave output?

### ISSUE THREAD

**Issue by jianke777** [NOAA-EMC/WW3#224]
I am trying to figure our why there are a lot of gaps in the swell and wind wave data output. Are these low values or no values? Can anyone help to confirm? Thanks.

**Comment by aliabdolali** [comment]
Hi @jianke777 your issue is not exactly a code development issue and is not clearly explained, it is more like a user needing help with a problem for an application. Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users
