### ISSUE TITLE
help me for use active boundary in model

### ISSUE THREAD

**Issue by mehdiiikeb** [NOAA-EMC/WW3#240]
Hi guys please help me for use active boundary from multi_1.global From NOAA 
first step i download data from multi_1.global in same lat 17 and lon (46 - 86) grib2
and in wave match i change mask file to active boundary set code 2 in lat 17 and lon (46 - 86) grib2

What else should I do?...؟؟؟
And where and how should I apply open border information?
Thankful

**Comment by aliabdolali** [comment]
Hi @mehdiiikeb your issue is not exactly a code development issue and is not clearly explained, it is more like a user needing help with a problem for an application. Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users
