### ISSUE TITLE
WW3 speedup & optimization

### ISSUE THREAD

**Issue by kihangyoun** [NOAA-EMC/WW3#244]
Hello everybody,

I'm working on improving the WW3's computational performance.
I'll will share some information about the current situation.

1. The domain of WW3 consists of 3 nests.
2. The maximum MPI rank is 900.
   * Not performed when exceeding 900.
3. Hybrid (MPI+OpenMP) is being used, but OpenMP parallel performance is not good 
   * Even if 4 OpenMP threads are used, a double performance improvement cannot be expected.
4. The optimization flags are as follows
   * "-O3 -assume byterecl -ip -xCORE-AVX512"
5. Separation of I/O nodes has no significant performance improvement.

In the current situation, I have to make at least 2x performance improvement (due to execution timeout).
I'd like to know about other options I might try.
Please tell us if there is a lack of explanation or if there is a new optimization method.

Regards,
Kihang

**Comment by aliabdolali** [comment]
Hi @kihangyoun  your issue is not exactly a code development issue, it is more like a user needing help with a problem for an application. Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users

**Comment by kihangyoun** [comment]
Hi @aliabdolali,
Your information is very helpful for me.
I'll send my question to WW3 user forum you recommend.
Thank you for your help.
