### ISSUE TITLE
w3_automake issue

### ISSUE THREAD

**Issue by JacquesJacob** [NOAA-EMC/WW3#253]
I am trying to compile WW3 in a CENTOS 7. After the installation, I am getting this error after run w3_automake script:

Processing ww3_multi
---------------------
ad3 : processing constants 
ad3 : processing w3tidemd 
ad3 : processing w3uqckmd 
mv: cannot stat ‘constants.o’: No such file or directory
mv: cannot stat ‘w3tidemd.o’: No such file or directory
mv: cannot stat ‘w3uqckmd.o’: No such file or directory
ad3 : processing w3servmd 
mv: cannot stat ‘w3servmd.o’: No such file or directory
ad3 : processing w3gsrumd 
ad3 : processing w3arrymd 
ad3 : processing w3cspcmd 
ad3 : processing wmunitmd 
mv: cannot stat ‘w3gsrumd.o’: No such file or directory
mv: cannot stat ‘w3arrymd.o’: No such file or directory
mv: cannot stat ‘w3cspcmd.o’: No such file or directory
mv: cannot stat ‘wmunitmd.o’: No such file or directory

**Comment by ukmo-ccbunney** [comment]
Hi @JacquesJacob,

This GitHub Issues page is intended for developers to raise bugs/issues with the code.

The problem you are having looks more like an issue with your setup, rather than the model itself. Please could you direct questions like this to the WW3 User Mailing list here: 
   
 * https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users

However, to offer a little advice, I would suggest that you look at the *.err and *.out files in your SCRATCH directory - they might give you a clue as to why the compiler is failing. If you can't see an obvious reason, please make a post in the user list above.

Good luck!
Chris.

**Comment by JacquesJacob** [comment]
> Hi @JacquesJacob,
> 
> This GitHub Issues page is intended for developers to raise bugs/issues with the code.
> 
> The problem you are having looks more like an issue with your setup, rather than the model itself. Please could you direct questions like this to the WW3 User Mailing list here:
> 
> * https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users
> 
> However, to offer a little advice, I would suggest that you look at the *.err and *.out files in your SCRATCH directory - they might give you a clue as to why the compiler is failing. If you can't see an obvious reason, please make a post in the user list above.
> 
> Good luck!
> Chris.

Tks Chris!!
