### ISSUE TITLE
Enable direct use of atmospheric model wind stress by source terms

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#337]
This development proposes to add a new flux processing option, FLX5 that enable the wind stresses developed in an atmosphere model to be applied to the WAVEWATCH III source terms.

Initial development will concentrate on compatibility of ST4 and ST6 with Unified Model winds (Met Office)

**Comment by ukmo-ansaulter** [comment]
@ukmo-ccbunney are you able to add @ukmo-nievesvaliente to the developers list so we can assign Nieves as the main developer?

**Comment by ukmo-juan-castillo** [comment]
Work on this issue can not start until PR https://github.com/NOAA-EMC/WW3/pull/285 is completed.

**Comment by ukmo-ccbunney** [comment]
> 
> 
> @ukmo-ccbunney are you able to add @ukmo-nievesvaliente to the developers list so we can assign Nieves as the main developer?

@ukmo-ansaulter Nieves is already part of the "Wave R&D Team" in our Organisation. I think @ukmo-nievesvaliente will need to be added as a "Collaborator" in the NOAA repo. @aliabdolali - are you able to do this?

**Comment by ukmo-juan-castillo** [comment]
At the moment the wind switches WNTN and WNTXN are used to choose between different time and space interpolation for the wind stress field. It may be necessary to create new switches to distinguish between wind and stress interpolations, but I do not see a great problem leaving it as it is because it should not be possible to drive the model at the same time with wind and stress. There are no checks in the code to avoid this last situation, which should be properly taken care of.
