### ISSUE TITLE
Mesh not accepted in ww3_grid

### ISSUE THREAD

**Issue by ghost** [NOAA-EMC/WW3#365]
When I run `ww3_grid` with an input GMSH unstructured mesh, I get the following error:

```+TRACE......COMPUTE SI, TRIA und CCON
+TRACE......COMPUTE CELLVERTEX
+TRACE......COMPUTE IE_CELL and POS_CELL

 Sub-grid information        : Not available.
 IP=       23270  IP2=       22721  IP3=       22720
 We have a dramatic inconsistency
```

It does not happen for all the meshes, and I assume that it is related to the unstructured meshe's quality. But is this kind of error common or is it a bug? What does IP, IP2 and IP3 mean?

Thanks in advance.

**Comment by aliabdolali** [comment]
Hi @nunormont 
Your mesh should follow WW3 standard for unstructured meshes, so we have added a check routine to find those problematic elements (overlapping, negative area, etc). 
The IP, IP2, and IP3 are the index of x and y coordinates of the problematic triangle (it loops through all the elements). For example, nodes 23270, 22721 and 22720 are making a triangle. In this case, it is not following WW3 standards.
Please take a look at regtests/ww3_tp2.17/input/*msh to see the unstructured mesh format. It starts with the longitude and latitude of nodes, then element connections are defiend.

**Comment by ghost** [comment]
Ok, thanks!

**Comment by ccoulet** [comment]
Hi
I reopen this issue as for me there is still a bug for GMSH unstructured grid.
I've got different meshes which works well with the official release (6.07) and which are now always returning the same message about dramatic inconsistency...
I'm currently investigating.
For me the problem is on Get_boundary were some of the Prev/Next nodes are sometimes not on the boundary itself. This relies probably on the a kind of first element found win so elements on the boundaries should have a lower indices than the element inside the domain. 
Thanks in advance

**Comment by aliabdolali** [comment]
@ccoulet I'd suggest visualizing your mesh and checking the element the model is giving you an inconsistency error. If it is clockwise, turn them counter-clockwise. It was a bug in 6.07 and is now fixed, so the current development is correct. 
Sometimes, there are overlapping elements, which most of the mesh generator tools do not check, but WW3 checks for them.

**Comment by ccoulet** [comment]
@aliabdolali 
Already done and the mesh are correct.

**Comment by aliabdolali** [comment]
@aronroland do you have any suggestion for @ccoulet?

**Comment by aronroland** [comment]
It means that your mesh is broken. E.g. connection table is not consistent can i have the grid for my curiosity?

**Comment by ccoulet** [comment]
[mesh_pb.zip](https://github.com/NOAA-EMC/WW3/files/8756484/mesh_pb.zip)
Here it is

**Comment by ccoulet** [comment]
@aliabdolali the problem is in your code!
In Spatial grid, there is a call to FIX_PERIODCITY without any protection if the model is cartesian and not global...
Then in some case, some conditions of FIX_PERIODCITY are verified and change of X-Y values are done which leads to false distance, and then to false area and as a consequence to consider the orientation wrong even there are CCW.
2 days of works to identify step by step where the problem is!

**Comment by aliabdolali** [comment]
@ccoulet thanks for finding this issue. I'll open an issue to fix it in the code. WW3 is a community model and we always welcome our developer/users to report issues and we are open to suggestions for code enhancements.

**Comment by ccoulet** [comment]
I agree about the community model but this kind of bug shouldn't exist with regression tests...
You should also verify the code coverage of the tests cases...
