### ISSUE TITLE
OUTID:  indexes outside of character array

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/WW3#487]
**Describe the bug**
The character array `OUTID` in `w3wavemd` is declared as length = 13, though is seen access index 15, where index variable `J=8`.

**To Reproduce**
Run the `ww3_ufs1.1` regtest in debug mode (i.e., after running `matrix_ncep`, edit the `run_test` command string in `matrix12` to have the compile flag/arg:  `-c intel_debug`, then run `matrix12`).

**Expected behavior**
WW3 will compile successfully, but will crash with a _forrtl: severe_ error as it starts to integrate at 00Z.

**Screenshots**
![image](https://user-images.githubusercontent.com/86749872/136108781-cfd2ecf7-baf4-42d9-852f-2f513110e4ef.png)

**Additional context**
N/A

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA since this is supposed to indicate writing a restart file, instead of having J=8 when determining the OUTID dimensions, I would vote going ahead and hard-coding that J value to 4 to write into the restart column.  Alternatively the dimension of OUTID could be updated and we could add a new column for the second stream of restart writes.     I don't know if others have preferences?

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA and I had an offline discussion, and the possibility of having both primary and secondary streams at the same time came up.  If we hard-coded the J value to 4 in that case, two symbols would have to be at the same location.  Based on this we thought / I'd vote for a new column to indicate secondary restarts.
