### ISSUE TITLE
"bus error" issue when running code

### ISSUE THREAD

**Issue by Agoni00** [NOAA-EMC/WW3#517]
Describe the bug
When I run the mode, when preprocessing the wind field data (from 1999 to 2001, the 6-hour wind field data), there will always be an error (core dumped)as shown in the figure.And generate a core file, according to the file, the query knows that the error is: Program terminated with signal 7, Bus error. what should I do? How can I solve it? 

![1636021648(1)](https://user-images.githubusercontent.com/92639723/140305104-6ead4e64-d63c-470c-a1e2-d856c0741806.jpg)
![1636024554(1)](https://user-images.githubusercontent.com/92639723/140305735-f135f6fa-057f-4a7b-b32b-b83195e70c90.jpg)

**Comment by aliabdolali** [comment]
@Agoni00
The bus error usually happens where there is no memory.
I would suggest testing ww3_prnc with a few time steps, to make sure it can go through. Also, you can check 
https://github.com/NOAA-EMC/WW3/wiki/FAQs-page#executing-heavy-serial-jobs
It might be due to a lack of memory on your login node, so you can use a larger memory on the computational core (It is machine-specific).

**Comment by Agoni00** [comment]
@aliabdolali 
I tried to run it for 4 days without any problems. So, my question is because of insufficient memory in the login node? Should I run on a compute node? Or how to expand the memory of my computational core？

**Comment by JessicaMeixner-NOAA** [comment]
Running on a compute node is a great thing to try.  Your sysadmins probably will appreciate that.  To get more memory per compute node, a typical strategy is to use less cpus/node than the total number of cpu's available.  Another strategy could be to use a big memory node if its available on your HPC.

**Comment by JessicaMeixner-NOAA** [comment]
@Agoni00 I'm going to close this issue.  If you have additional issues please re-open or create a new issue.
