### ISSUE TITLE
Add Doxygen documentation support

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/WW3#547]
**Is your feature request related to a problem? Please describe.**
No.  This feature would extend the current documentation using the source code documentation tool, [_doxygen_](https://www.doxygen.nl).

**Describe the solution you'd like**
The WW3 code base has been annotated with approved doxygen markup templates.  The result is doxygen is able to automatically generate formatted documentation from the WW3 source, for both on/off-line viewing.

**Describe alternatives you've considered**
Doxygen is the de facto standard and is the tool decided on for this task.

**Additional context**
I will be working on a PR for this issue.  I will have prototype templates to share shortly for each code unit (program, subroutine, etc).

**Comment by edwardhartnett** [comment]
Instead of having the doxyfile in the top-level directory, it should be in a directory called "docs".

Instead of checking in the Doxyfile, check it in as Doxyfile.in, and then you can use variable substitution to set the version number of the documentation automatically. For example, see any of the NCEPLIBS projects. Then the documentation contains the version number in a prominent place, and it is never wrong. For example:

![image](https://user-images.githubusercontent.com/38856240/148646862-9a23807b-fd8a-4da6-a295-bf9cebaac1df.png)

Note the version number, 3.4.5, prominently displayed next to the package name at the top.

In the top level CMakeLists.txt file we have:

```
# Determine whether or not to generate documentation.
option(ENABLE_DOCS "Enable generation of doxygen-based documentation." OFF)
if(ENABLE_DOCS)
  find_package(Doxygen REQUIRED)
endif()
add_subdirectory(docs)  

```
In the docs directory we have a CMakeLists.txt file like this:

```
 # This is the CMake file for building the docs directory of NCEPLIBS-g2.
#
# Ed Hartnett 10/8/20

IF(ENABLE_DOCS)

  # Create doxyfile.
  SET(abs_top_srcdir "${CMAKE_SOURCE_DIR}")
  SET(abs_top_builddir "${CMAKE_BINARY_DIR}")
  CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/Doxyfile.in ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile @ONLY)
  ADD_CUSTOM_TARGET(doc ALL
    ${DOXYGEN_EXECUTABLE} ${CMAKE_CURRENT_BINARY_DIR}/Doxyfile
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    COMMENT "Generating API Documentation with Doxygen" VERBATIM)

ENDIF(ENABLE_DOCS)

```
And in the Doxyfile.in we have:

`PROJECT_NUMBER         = @PROJECT_VERSION@
`

**Comment by edwardhartnett** [comment]
There are some settings you want to turn on in the Doxyfile:

```
# If the REFERENCED_BY_RELATION tag is set to YES then for each documented
# entity all documented functions referencing it will be listed.
# The default value is: NO.

REFERENCED_BY_RELATION = YES

# If the REFERENCES_RELATION tag is set to YES then for each documented function
# all documented entities called/used by that function will be listed.
# The default value is: NO.

REFERENCES_RELATION    = YES

```

These will automatically add to each subprogram what functions call it, and what it calls. Like this:
![image](https://user-images.githubusercontent.com/38856240/148647002-9fa51167-a089-4fef-b108-791595f16adc.png)

Note the last two lines, which are generated automatically by doxygen. This is a vast improvement to having programmers manually maintain these lists of called and calling functions, since such manual list are almost always incomplete or outdated.

**Comment by edwardhartnett** [comment]
Here's a presentation on Doxygen I gave to the EMC:
[Doxygen for Fortran Science Codes (1).pdf](https://github.com/NOAA-EMC/WW3/files/7833327/Doxygen.for.Fortran.Science.Codes.1.pdf)


Here's another that I gave the NCEPLIBS team (or maybe the UFS team - can't remember...)

[Doxygen and the UFS Code.pdf](https://github.com/NOAA-EMC/WW3/files/7833331/Doxygen.and.the.UFS.Code.pdf)

**Comment by edwardhartnett** [comment]
Here's a slide from on the presentations that's relevant to this effort. The closer you adhere to the conventions we are using for NCEPLIBS and UFS code, the easier it will be to easily develop and maintain good and consistent documentation across the organization: 

![image](https://user-images.githubusercontent.com/38856240/148647218-ef131f7b-a7fc-4c58-b317-c943b98b4e1c.png)

**Comment by edwardhartnett** [comment]
Supporting multiple versions of the documentation (ex. master vs. last released version) is easily accomplished on the gh-pages branch. See NCEPLIBS-g2c for an example of how this is done.

**Comment by MatthewMasarik-NOAA** [comment]
Hey @edwardhartnett, I just caught that these comments were here, sorry I didn't catch sooner..  I'm about to submit a new PR on a different branch.  It will just add a markdown file that simply is a reference for the required tag headers for each Fortran unit (file, program, subroutine, etc.).  They are exactly those that have been posted and you have commented on.  I'm scraping this one because I did not want there to be any documentation or code marked up in this PR, so I thought it easiest to start with a fresh clone.  I will be closing this one and pointing to the new one.

Regarding the comments above:
* I will include in the new PR a folder 'docs', and it will have our current config file.  I've already renamed it Doxygen.in.
* I believe we will want to do version numbers exactly how you've described.  
* I've made the changes Doxygen.in regarding the two `REFERENCE`-related settings.

**Comment by MatthewMasarik-NOAA** [comment]
Whoops.  I'll close the other PR.  The new PR will reference this issue.

**Comment by MatthewMasarik-NOAA** [comment]
This issue was intended for the header templates, which has been merged, so this will be closed now.  The follow-on issue with a running list of marked-up source files is ongoing, and located here:  https://github.com/NOAA-EMC/WW3/issues/586.
