### ISSUE TITLE
Bit for bit differences in mod_def files for regtests

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#61]
Need to check previous svn issues that explain differences in mod_def files for some test cases (ww3_tp2.7, ww3_ts4 and mww3_test_07).

**Comment by mickaelaccensi** [comment]
Hi @aliabdolali  and @ajhenrique ,

about ww3_tp2.7 and mww3_test07, they are b4b on my hpc with datarmor_intel_debug compiler keyword. I use intel-fc-18/18.0.1.163 and impi/2018.1.163

in the object of this issue, you talk about mod_def file b4b differences, in my case it's only affecting out_grd and/or restart files.

all my bug fixes are in branch  https://github.com/umr-lops/WW3/tree/bugfix/b4b

[SOLVED] about ww3_ts4, I found a bug which should correct the b4b problem for "ww3_ts4/input_rg_multi". we need to initialize all variables in TYPE  SGRD

[TODO] there is still an error on regtest "ww3_ts4/work_ug_MPI" when running ww3_ounf, I get an error message "floating divide by zero". I will investigate it

[SOLVED] Another b4b difference on restart.* in mww3_test03 happen when using grdset_e with switch UQ and MPI combined with PR2 or PR3 and SCRIP, otherwise with other switches it's b4b.. and it affects restart file and/or out_grd depending on the IOSTYP value. I have investigated it and the error is in w3wdatmd :
instead of
      WDATAS(IMOD)%UST   (:) = 1.E-5
use
      WDATAS(IMOD)%UST   (0:NSEATM) = 1.E-5

[TODO] I found a b4b difference on out_grd.* in mww3_test03 for all regtests using grdset_d2 which implies the load balancing. Deactivating all RESOURCE%COMM_FRAC permits to produce b4b outputs. I will investigate it

**Comment by ajhenrique** [comment]
@mickaelaccensi this is awesome. We will try this at our end. Thanks!

**Comment by mickaelaccensi** [comment]
@aliabdolali , I think you can close this issue. I opened 2 other issues for b4b issue on mww3_test_03

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali @mickaelaccensi can we close this issue?

**Comment by mickaelaccensi** [comment]
I do it.
there is still the b4b difference in mww3_test_03 which is known and not easy (even possible?) to solve.
