### ISSUE TITLE
A question about the calculation of Stokes velocity drift on the surface

### ISSUE THREAD

**Issue by Agoni00** [NOAA-EMC/WW3#776]
In the program w3iogomd.ftn, we can see the calculation of the Stokes drift speed, but I found that the calculated speed is too small, then I uncommented these two lines and the speed is not too small, so It seems that uncommenting the calculated speed is more accurate, I want to know why the source program to the two line commented out? See the following figure for the source code details.

![image](https://user-images.githubusercontent.com/92639723/187814445-008fd8c3-5afe-4918-8dfe-0044965dc91f.png)

**Comment by CarstenHansen** [comment]
@qingli411 is working in issue #669 on making the Stokes tail extension an optional feature, and I suggest that you share your experience in a discussion on that project. I don't consider this out-commenting a bug, and they cannot be chosen by default, since the adequate formulae depends on the tail power and on the directional distribution in the tail attached at the frequency band NK. I am thinking that if you set up WW3 with suitable parameters in the ST6 source terms (or ST4 in the develop branch with the Romero parameters), and if NK is large enough and (practically) always within a f^{-5} tail, then applying the out-commented two lines may be consistent.

**Comment by JessicaMeixner-NOAA** [comment]
I'm going to second @CarstenHansen comment and ask to move further discussion on this topic to https://github.com/NOAA-EMC/WW3/issues/669.
