### ISSUE TITLE
run_cmake_test force to copy ww3_prtide

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#837]
**Describe the bug**
run_cmake_test always try to copy the non-SHRD exe from the build directory to path_e even if ww3_prtide was not compiled (switch TIDE not present in the switch file)

**To Reproduce**
when running almost the regtests

**Expected behavior**
in run_cmake_test, add a test if file exists
    if [[ -e $path_build/install/bin/ww3_prtide ]] ; then
      cp $path_build/install/bin/ww3_prtide $path_e/
    fi

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi good idea! Instead of just checking that it exists, should we only even try to copy if the TIDE switch is there, that way then if that does not exist we could have an error?      Should we do that for all of the executables perhaps even?  Have a list of exes that  need to be copied, and if they don't exist, exit with an error?
