### ISSUE TITLE
Problem with the execution of the ww3_multi program in 7.14 version

### ISSUE THREAD

**Issue by mdeoto** [NOAA-EMC/WW3#932]
Hi Everyone,

Recently, I downloaded and compiled WW3 *version 7.14* from this github. I have set up the compilation using the intel compiler, running from the main directory via the following command line:

*./model/bin/w3_setup model -c intel -s prueba*

prueba refers to **switch_prueba** and contains the following list of switches:

F90 NOGRB NOPA LRB4 SHRD PR3 UQ FLX2 LN1 ST2 STAB2 NL1 BT1 DB1 MLIM TR0 BS0 IC0 IS0 REF0 XX0 WNT1 WNX1 CRT1 CRX1 O0 O1 O2 O3 O4 O5 O6 O7 O11 O14

The next step was to compile the programs to be used in the test cases through next command line:

*./model/bin/w3_make ww3_grid ww3_strt ww3_prep ww3_multi gx_outf*

That is, I want to perform a case of nesting. As a result, the following executables were generated in the **exe** directory (Fig. 1),

![Fig_1](https://user-images.githubusercontent.com/111830135/222604052-4cb234c5-9191-46d2-8e95-13f898d9c208.png)

Thus, these programs generated a number of **log** files hosted in the **tmp** directory. Only one program had documented errors (warnings): **w3arrymd**, see below (Fig. 2):

![Fig_2](https://user-images.githubusercontent.com/111830135/222604057-b0e7a485-13b0-457a-8382-c9ac82e56193.png)

Once the installation and compilation stage was finished, I decided to perform a nesting test case. This case is hosted in the **cases** directory and is named mww3_case_02 (Fig. 3 -highlighted in a white square- screenshot taken captured from page 250 in [manual]( https://raw.githubusercontent.com/wiki/NOAA-EMC/WW3/files/manual.pdf))

![Fig_3](https://user-images.githubusercontent.com/111830135/222604059-a88c60ed-30ae-4225-a6cd-3dbae85317fd.png)

Previously to run this script, I correctly modified the paths on my own system, unset the forcing and set the initial conditions, see figure below (Fig. 4)

![Fig_4](https://user-images.githubusercontent.com/111830135/222604061-29d4c6d2-c809-4c65-95bb-44f26b5a4bee.png)

In this case only use sequential running, so **mpi** parallelization is unsetting. Next, show the results from the execution (Fig. 5), note the error in the main program (highlighted in a white square)

![Fig_5](https://user-images.githubusercontent.com/111830135/222604068-43eb8914-8fc3-4570-8d65-febe881b3b3a.png)

The main hypothesis I have is that I am defining the **ww3_multi.inp** file wrong, however I have tried with other test cases and I also have the same error. I provide below a screenshot of this file (Fig. 6),

![Fig_6](https://user-images.githubusercontent.com/111830135/222604071-2b1ddc9f-7a9d-446d-9d36-64978cd54448.png)

Finally, **ww3_multi.inp** file is contained in a temporal directory with the other input files that are used to running the model, see this directory below (Fig. 7),

![Fig_7](https://user-images.githubusercontent.com/111830135/222604072-2e4695c0-aa23-41c6-af33-d8e8e2fafacb.png)

and, the **log.mww3** file (highlighted in a white square) hosted in this directory does not give me much information, see below (Fig. 8),

![Fig_8](https://user-images.githubusercontent.com/111830135/222604075-91925fdd-13dc-4e66-98ba-24f07e6f6eb3.png)

Finally, after the execution, an output directory has been generated with the following files (Fig. 9).

![Fig_9](https://user-images.githubusercontent.com/111830135/222604076-19748142-421b-4a74-9d8a-fdbd80e3e2d7.png)

As you can see, **ww3_grid** and **ww3_start** seem to work reliably.

So, what is the source of the input error? I would appreciate a lot of help

**Comment by EmilioEchevarria** [comment]
Hola Mati! :) 

I haven't tried to reproduce this, but yes there is something wrong with your ww3_multi.inp file. Just a guess: you point to the WW3 manual v6.07, and you installed v7.14. Having a look here: https://github.com/NOAA-EMC/WW3/blob/develop/model/inp/ww3_multi.inp#L76, I believe the number of forcing fields in your .inp file should be higher (all the 'no' in your file) . 

If that's the issue I believe you should be getting that error in line 849 of `wminitmd.F90` (https://github.com/NOAA-EMC/WW3/blob/develop/model/src/wminitmd.F90#L849-L850). It's worth compiling WW3 with `-g -traceback` options if you're not doing that already.

Also, have a look here: https://github.com/NOAA-EMC/WW3/blob/develop/model/inp/ww3_multi.inp#L182-L191

It seems you're not trying to run regtest `mww3_test_02` but a modified version of it?

I hope that helps.
Emilio

Edit: Don't worry about the warning you got, `E8.3` is the edit descriptor, and it's telling you to use 3+7 instead of 8 for the total width of the field, or number you're trying to write.

**Comment by mdeoto** [comment]
Hi Emi!

Cómo andás?

Thank you very much for your answer, it worked! In particular, I had wrongly configured the **ww3_multi.inp** because I was relying on an old version.
