### ISSUE TITLE
field corruption at the restart-writing frequency (cross-posting from UFS)

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/WW3#948]
**Describe the bug**

**NOTE:** This is a cross-post of UFS Issue [1556](https://github.com/ufs-community/ufs-weather-model/issues/1556).

An issue has been found relating to the domain decomposition, the restart-write frequency and the failure to reproduce when changing the decomp for WW3.

The test case is the ATM-WAV app, coupled through CMEPS. This app resides in within my fork and uses as a test case a global (77S-85N) unstructured mesh with the MOM6 1-deg tripole land mask (no land points exist in the mesh). The time-stepping mode is explicit for WW3. 

In ww3_shel.nml, the following values are set:

```
&output_date_nml
  date%field%outffile  = '1'
  date%field%stride    = '720'
  date%restart2%stride = '3600'
```

When run on 5PEs for WW3, the following decomposition is used:

![emesh decomp](https://user-images.githubusercontent.com/40498404/223487636-d9a39852-d60e-4533-aff9-bf3a2ed63160.jpg)

Using the mediator history file, the following fields for the export of ``z0`` from the wave model are shown at the timestep prior to the restart write, at the restart write, and following the restart write. Note the value of ``z0`` has been multipled by 1.0e3. 

![wavImp_Sw_z0](https://user-images.githubusercontent.com/40498404/223488199-84e4640f-59af-41b3-a8c1-44518166d56e.jpg)

The export of ``z0`` is clearly corrupted on the last decomposition PE. This occurs each time the restart file is written. If N PEs are used for WW3, then every Nth value of ``UST`` has the value of 1.0e-4.

Using simple print statements, this was found to be related to ``UST`` and to occur just after the ``MPI_STARTALL`` line in ``w3wavemd.F90``. 

```
#ifdef W3_MPI
        IF ( FLOUT(8) .AND. NRQRS.NE.0 ) THEN
          IF ( DSEC21(TIME,TONEXT(:,8)).EQ.0. ) THEN
	    CALL MPI_STARTALL ( NRQRS, IRQRS , IERR_MPI )
            FLGMPI(8) = .TRUE.
            NRQMAX    = MAX ( NRQMAX , NRQRS )
#endif
```

Commenting out the call to ``MPI_STARTALL`` removed the corruption. This is a repeat of the previous figure with the commented out line:
![fix wavImp_Sw_z0](https://user-images.githubusercontent.com/40498404/223494832-9b33d329-cb6c-4b64-8957-0d29b169b27c.jpg)

With this line commented out, the ATM-WAV case run out for 24 hours on either 20PE or 30PE reproduces. The 30PE case also restart reproduces. 

In the ATM-WAV case, failure to reproduce w/ changing decomposition is due to the corrupted ``z0`` field which depends explicitly on the location of the final decomposition element and which occurs when WW3 writes a restart file. This is confirmed by setting ``date%restart2%stride`` to a value outside of the total run length. This gives reproducibility across tasks with no code modification. 

Finally, WW3 history files written to out do not show any corruption of the field ``ust``. I believe this is because the ``z0`` field is put into the export state after WW3 has completed it's model advance, including any model output and restart writing.

**Comment by aronroland** [comment]
@DeniseWorthen many thanks for this comprehensive work and description of the issue. The mpi_start stuff is something we avoided on the unstructured and it is something that was coded a long time ago. In order to fully understand what it is going there I would need some time.

**Comment by DeniseWorthen** [comment]
Thanks @aronroland. I know you had originally suggested a code modification where the startall doesn't get called w/ pdlib, but I think a better solution is in my current PR (#949). 

Essentially in ``w3init`` I was able to insert a check like so

``IF ((FLOUT(4) .OR. FLOUT(8)) .and. (.not. LPDLIB)) THEN``

this results in nrqrs being 0 and so the code block in ``w3wavemd`` is not executed since it checks for nrqrs>0.

I made a similar fix for the FLOUT(1),(7) but in that case, I needed to add a small call to ``w3xdma`` in the pdlib_vec routine.

**Comment by aronroland** [comment]
Hi Denise, 

 

I was absent some days so I need to get some overview, sorry I have missed something. I will look at the below as well. 

 

Cheers

 

Aron

 

Von: Denise Worthen ***@***.***> 
Gesendet: Montag, 20. März 2023 18:53
An: NOAA-EMC/WW3 ***@***.***>
Cc: Aron Roland ***@***.***>; Mention ***@***.***>
Betreff: Re: [NOAA-EMC/WW3] field corruption at the restart-writing frequency (cross-posting from UFS) (Issue #948)

 

Thanks @aronroland <https://github.com/aronroland> . I know you had originally suggesting a code modification where the startall doesn't get called w/ pdlib, but I think a better solution is in my current PR (#949 <https://github.com/NOAA-EMC/WW3/pull/949> ).

Essentially in w3init I've was able to insert a check like so

IF ((FLOUT(4) .OR. FLOUT(8)) .and. (.not. LPDLIB)) THEN

this results in nrqrs being 0 and so the code block in w3wavemd is not executed since it checks for nrqrs>0.

I made a similar fix for the FLOUT(1),(7) but in that case, I needed to add a small call to w3xdma in the pdlib_vec routine.
