### ISSUE TITLE
Invalid Fortran unit number in w3uostmd

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#96]
The W3UOSTMD module opens a file with unit number 100. This is an invalid unit number when using Cray Fortran; excerpt from the the Cray Fortan Documention:

> File Unit Numbers
>The values of INPUT_UNIT, OUTPUT_UNIT, and ERROR_UNIT defined in the ISO_Fortran_env module are 100, 101, and 102, respectively. These three unit numbers are reserved and may not be used for other purposes. 

See line 159 of w3uostmd.ftn:
https://github.com/NOAA-EMC/WW3/blob/92cb41f70e91da97be9e5cd8bfee1de0a569f676/model/ftn/w3uostmd.ftn#L159

I recommend changing the unit number (3rd argument) to **110**

**Comment by JessicaMeixner-NOAA** [comment]
For ESMF and possibly other coupled models, we need to have file unit numbers that are not already being used by another model.   It would be nice if maybe we put the 100 as a variable with comment that it's a file unit (set at 110 for now), so that we can easily find this in the future if this becomes an issue.

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA Ok - I shall do that.
@ajhenrique, do we consider this a hotfix, or shall I make it a bugfix in develop?
